package be.woutzah.litebansbridge.message.domain;

public enum MessageType {
    REVOKE_DISCORD_CHAT_BANNED,
    REVOKE_DISCORD_CHAT_MUTED,
    PUNISHED_PERMABANNED,
    PUNISHED_BANNED,
    PUNISHED_PERMAMUTED,
    PUNISHED_MUTED,
    PUNISHED_WARNED,
    PUNISHED_KICKED,
    STAFFLOG_PERMABANNED,
    STAFFLOG_BANNED,
    STAFFLOG_PERMAMUTED,
    STAFFLOG_MUTED,
    STAFFLOG_WARNED,
    STAFFLOG_KICKED
}
